name: Lint and build
on:
  push:
    branches:
    - main
    tags:
    - 'v*'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Install libpam0g-dev
      run: sudo apt install libpam0g-dev
    - name: Checkout
      uses: actions/checkout@v2
    - name: Setup Rust toolchain
      uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: stable
        components: clippy
        override: true
    - name: Setup cache
      uses: actions/cache@v2
      with:
        path: |
          ~/.cargo/bin/
          ~/.cargo/registry/index/
          ~/.cargo/registry/cache/
          ~/.cargo/git/db/
          target/
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
    - name: Run cargo clippy
      uses: actions-rs/cargo@v1
      with:
        command: clippy
        args: -- -D clippy::all
    - name: Run cargo build
      uses: actions-rs/cargo@v1
      with:
        command: build
        args: --release
    - name: Copy build artifact
      run: cp target/release/libpam_bacchus.so pam_bacchus.so
    - name: Upload build artifact
      uses: actions/upload-artifact@v2
      with:
        name: pam_bacchus
        path: pam_bacchus.so
    - name: Create release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: |
          pam_bacchus.so
